config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "streams#index"

  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :streams, only: [:show] do
    post :start, on: :collection
    post :stop, on: :collection
    post :auth, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stream.rb
class Stream < ApplicationRecord
  has_one_attached :recording
  has_many_attached :frames
  validates :stream_key, presence: true

  def generate_frames_from_stream
    FfmpegService.new(self).execute
  end

  def stop_jobs
    FfmpegService.new(self).quit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  skip_before_action :verify_authenticity_token  # Disable CSRF for RTMP callbacks
  before_action :get_stream_key, only: [:start, :stop]

  # Index action
  def index
    @streams = Stream.all
  end

  # Show stream
  def show
    @stream = Stream.find(params[:id])
  end

  # Authentication logic
  def auth
    render plain: 'OK', status: :ok
  end

  # Start stream with real-time analysis
  def start
    return head :bad_request unless valid_stream_key?(stream_key)
    stream = Stream.new(stream_key: stream_key) # Use stream_key for the Stream instance
    if stream.save
      stream.generate_frames_from_stream
      logger.info "Stream #{stream.stream_key} started"
    else
      logger.error "Error starting stream #{stream.stream_key}: #{stream.errors.full_messages}"
    end
    render plain: 'OK', status: :ok
  end

  # Stop stream
  def stop
    @stream = Stream.where(stream_key: stream_key).last
    @stream.stop_jobs
    render plain: 'OK', status: :ok
  end

  private

  # Check if stream key is valid
  def valid_stream_key?(stream_key)
    stream_key == 'test_stream' 
  end

  def get_stream_key
    @stream_key ||= params[:name]
  end

  def stream_key
    @stream_key
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streams/index.html.erb
<h1>Streams</h1>

<table>
    <% @streams.each do |stream| %>
        <tr>
            <td>
                <%= stream.frames.count %>
            </td>
            <td>
                <%= Redis.new.get("stop_job_#{stream.id}").present? ? "true" : "false" %>
            </td>
                <% stream.frames.first(5).each do |frame| %>
                    <td>
                <%= image_tag frame, size: "100x100" %>
                </td>
            <% end %>
            <td>
                <%= link_to stream.stream_key, stream_path(stream) %>
            </td>
        </tr>
    <% end %>
</table>

app/views/streams/show.html.erb
<h1><%= @stream.stream_key %></h1>

<h2>Frames</h2>
<ul>
  <% @stream.frames.each do |frame| %>
    <li>
      <%= image_tag frame %>
    </li>
  <% end %>
</ul>